:development:
  jquery: http://code.jquery.com/jquery-1.7.js
  underscore: http://documentcloud.github.com/underscore/underscore.js
  microevent: https://raw.github.com/jeromeetienne/microevent.js/master/microevent-debug.js
:production:
  jquery: http://code.jquery.com/jquery-1.7.min.js
  underscore: http://documentcloud.github.com/underscore/underscore-min.js
  microevent: https://raw.github.com/jeromeetienne/microevent.js/master/microevent.js
